vich_uploader:
    db_driver: orm
    mappings:
        produit_images:
            uri_prefix: /uploads/produits
            upload_destination: '%kernel.project_dir%/public/uploads/produits'
            namer: vich_uploader.namer_smart_unique
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false

        animal_photo:
            uri_prefix: /uploads/animals
            upload_destination: '%kernel.project_dir%/public/uploads/animals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false